from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.login_up, name='login_up'),
    path('home/', login_required(views.home), name='home'),
    path('logout/', login_required(auth_views.logout), name='logout'),
    path('Unidad_Organizacional/', login_required(views.gestionar_unidad_org), name='gestionarUnidadOrg'),
    path('Calificacion/', login_required(views.gestionar_calificacion), name='gestionarCalificacion'),
    path('Departamento/', login_required(views.gestionar_departamento), name='gestionarDepartamento'),
    path('Cargo/', login_required(views.gestionar_cargo), name='gestionarCargo'),
    path('Especialidad/', login_required(views.gestionar_especialidad), name='gestionarEspecialidad'),
    path('Seccion_Sindical/', login_required(views.gestionar_seccion_sindical), name='gestionarSeccionSindical'),
    path('Adicionar_Unidad_Organizacional/', login_required(views.adicionar_uo), name='adicionarUO'),
    path('Editar_Unidad_Organizacional/<int:pk>/', login_required(views.editar_uo), name='editarUO'),
    path('Detalle_Unidad_Organizacional/<int:pk>/', login_required(views.DetalleUo.as_view()), name='detalleUO'),
    path('Eliminar_Unidad_Organizacional/<int:pk>/', login_required(views.eliminar_uo), name='eliminarUO'),
    path('Adicionar_Seccion_Sindical/', login_required(views.adicionar_ss), name='adicionarSS'),
    path('Editar_Seccion_Sindical/<int:pk>/', login_required(views.editar_ss), name='editarSS'),
    path('Detalle_Seccion_Sindical/<int:pk>/', login_required(views.DetalleSs.as_view()), name='detalleSS'),
    path('Eliminar_Seccion_Sindical/<int:pk>/', login_required(views.eliminar_ss), name='eliminarSS'),
    path('Adicionar_Departamento/', login_required(views.adicionar_departamento), name='adicionarDepartamento'),
    path('Editar_Departamento/<int:pk>/', login_required(views.editar_departamento), name='editarDepartamento'),
    path('Detalle_Departamento/<int:pk>/', login_required(views.DetalleDepartamento.as_view()),
         name='detalleDepartamento'),
    path('Eliminar_Departamento/<int:pk>/', login_required(views.eliminar_departamento), name='eliminarDepartamento'),
    path('Adicionar_Cargo/', login_required(views.adicionar_cargo), name='adicionarCargo'),
    path('Editar_Cargo/<int:pk>/', login_required(views.editar_cargo), name='editarCargo'),
    path('Detalle_Cargo/<int:pk>/', login_required(views.DetalleCargo.as_view()), name='detalleCargo'),
    path('Eliminar_Cargo/<int:pk>/', login_required(views.eliminar_cargo), name='eliminarCargo'),
    path('Adicionar_Calificacion/', login_required(views.adicionar_calificacion), name='adicionarCalificacion'),
    path('Editar_Calificacion/<int:pk>/', login_required(views.editar_calificacion), name='editarCalificacion'),
    path('Detalle_Calificacion/<int:pk>/', login_required(views.DetalleCalificacion.as_view()),
         name='detalleCalificacion'),
    path('Eliminar_Calificacion/<int:pk>/', login_required(views.EliminarCalificacion.as_view()),
         name='eliminarCalificacion'),
    path('Adicionar_Especialidad/', login_required(views.adicionar_especialidad), name='adicionarEspecialidad'),
    path('Editar_Especialidad/<int:pk>/', login_required(views.editar_especialidad), name='editarEspecialidad'),
    path('Detalle_Especialidad/<int:pk>/', login_required(views.DetalleEspecialidad.as_view()),
         name='detalleEspecialidad'),
    path('Eliminar_Especialidad/<int:pk>/', login_required(views.eliminar_especialidad), name='eliminarEspecialidad'),
]
